In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("food_messy_dataset1.csv")
df

,order_id,restaurant_name,cuisine_type,meal_time,num_items,avg_item_price,discount_percent,delivery_distance_km,delivery_rating,customer_age,customer_gender,weekend,num_previous_orders,total_bill
0,1,Spice Garden,Indian,Lunch,3,180.5,10.0,2.3,4.5,28,Male,Yes,5.0,486.0
1,2,Pizza Palace,Italian,Dinner,2,350.0,0.0,5.1,3.8,34,Female,No,12.0,700.0
2,3,Burger Barn,American,Lunch,4,220.0,15.0,1.8,4.2,22,Male,Yes,2.0,748.0
3,4,Sushi Stop,Japanese,Dinner,5,410.0,5.0,7.2,4.9,41,Female,No,20.0,1947.5
4,5,Spice Garden,Indian,Breakfast,1,90.0,0.0,2.3,4.5,19,Male,No,0.0,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Noodle Nest,Chinese,Dinner,4,195.0,0.0,6.3,4.0,43,Female,No,29.0,780.0
196,197,Sushi Stop,Japanese,Lunch,5,410.0,20.0,7.2,4.9,24,Male,Yes,3.0,1640.0
197,198,Green Bowl,Healthy,Breakfast,2,280.0,10.0,3.5,4.7,37,Female,No,16.0,504.0
198,199,Taco Town,Mexican,Dinner,4,160.0,5.0,4.0,4.1,30,Male,No,10.0,608.0
199,200,Spice Garden,Indian,Lunch,3,180.5,0.0,2.3,4.5,22,Female,Yes,0.0,541.5

In [5]:
df.dtypes

order_id                  int64
restaurant_name          object
cuisine_type             object
meal_time                object
num_items                object
avg_item_price          float64
discount_percent        float64
delivery_distance_km    float64
delivery_rating          object
customer_age             object
customer_gender          object
weekend                  object
num_previous_orders     float64
total_bill              float64
dtype: object

In [6]:
df.shape

(200, 14)

In [7]:
df.isnull().sum()

order_id                0
restaurant_name         0
cuisine_type            0
meal_time               1
num_items               1
avg_item_price          1
discount_percent        1
delivery_distance_km    1
delivery_rating         1
customer_age            1
customer_gender         2
weekend                 1
num_previous_orders     1
total_bill              4
dtype: int64

In [8]:
df['num_items']=pd.to_numeric(df['num_items'],errors='coerce')

In [9]:
df.head()

,order_id,restaurant_name,cuisine_type,meal_time,num_items,avg_item_price,discount_percent,delivery_distance_km,delivery_rating,customer_age,customer_gender,weekend,num_previous_orders,total_bill
0,1,Spice Garden,Indian,Lunch,3.0,180.5,10.0,2.3,4.5,28,Male,Yes,5.0,486.0
1,2,Pizza Palace,Italian,Dinner,2.0,350.0,0.0,5.1,3.8,34,Female,No,12.0,700.0
2,3,Burger Barn,American,Lunch,4.0,220.0,15.0,1.8,4.2,22,Male,Yes,2.0,748.0
3,4,Sushi Stop,Japanese,Dinner,5.0,410.0,5.0,7.2,4.9,41,Female,No,20.0,1947.5
4,5,Spice Garden,Indian,Breakfast,1.0,90.0,0.0,2.3,4.5,19,Male,No,0.0,90.0

In [10]:
df['delivery_rating']=pd.to_numeric(df['delivery_rating'],errors='coerce')

In [11]:
df['customer_age']=pd.to_numeric(df['customer_age'],errors='coerce')

In [12]:
df['meal_time']=df['meal_time'].fillna(df['meal_time'].mode()[0])
df['meal_time']

0          Lunch
1         Dinner
2          Lunch
3         Dinner
4      Breakfast
         ...
195       Dinner
196        Lunch
197    Breakfast
198       Dinner
199        Lunch
Name: meal_time, Length: 200, dtype: object

In [13]:
df['num_items']=df['num_items'].fillna(df['num_items'].mean())

In [14]:
df['num_items']=df['num_items'].fillna(df['num_items'].mean())

In [15]:
print(df[df["avg_item_price"] < 0])

    order_id restaurant_name cuisine_type meal_time  num_items  \
84        85    Pizza Palace      Italian    Dinner        5.0

    avg_item_price  discount_percent  delivery_distance_km  delivery_rating  \
84          -350.0               5.0                   5.1              3.8

    customer_age customer_gender weekend  num_previous_orders  total_bill
84          32.0            Male     Yes                 10.0      1662.5

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
print((df["avg_item_price"] < 0).sum())

1

In [18]:
df = df[df["avg_item_price"] >= 0]

In [19]:
print((df["avg_item_price"] < 0).sum())

0

In [20]:
df['discount_percent']=df['discount_percent'].fillna(df['discount_percent'].mean())

C:\Users\vinut\AppData\Local\Temp\ipykernel_30284\91044276.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['discount_percent']=df['discount_percent'].fillna(df['discount_percent'].mean())

In [21]:
df['delivery_distance_km']=df['delivery_distance_km'].fillna(df['delivery_distance_km'].mean())

C:\Users\vinut\AppData\Local\Temp\ipykernel_30284\3513910881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['delivery_distance_km']=df['delivery_distance_km'].fillna(df['delivery_distance_km'].mean())

In [22]:
df['delivery_rating']=df['delivery_rating'].fillna(df['delivery_rating'].mean())

C:\Users\vinut\AppData\Local\Temp\ipykernel_30284\1034643060.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['delivery_rating']=df['delivery_rating'].fillna(df['delivery_rating'].mean())

In [23]:
df['customer_age']=df['customer_age'].fillna(df['customer_age'].median())

C:\Users\vinut\AppData\Local\Temp\ipykernel_30284\1941990880.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_age']=df['customer_age'].fillna(df['customer_age'].median())

In [24]:
df['customer_gender']=df['customer_gender'].fillna(df['customer_gender'].mode()[0])

C:\Users\vinut\AppData\Local\Temp\ipykernel_30284\3932388572.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_gender']=df['customer_gender'].fillna(df['customer_gender'].mode()[0])

In [25]:
df['weekend']=df['weekend'].fillna(df['weekend'].mode()[0])

C:\Users\vinut\AppData\Local\Temp\ipykernel_30284\3575004226.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weekend']=df['weekend'].fillna(df['weekend'].mode()[0])

In [26]:
df['num_previous_orders']=df['num_previous_orders'].fillna(df['num_previous_orders'].mean())

C:\Users\vinut\AppData\Local\Temp\ipykernel_30284\2229363312.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_previous_orders']=df['num_previous_orders'].fillna(df['num_previous_orders'].mean())

In [27]:
df['total_bill']=df['total_bill'].fillna(df['total_bill'].median())

C:\Users\vinut\AppData\Local\Temp\ipykernel_30284\2840291537.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_bill']=df['total_bill'].fillna(df['total_bill'].median())

In [28]:
df = df.drop("order_id", axis=1)

In [29]:
df.head()

,restaurant_name,cuisine_type,meal_time,num_items,avg_item_price,discount_percent,delivery_distance_km,delivery_rating,customer_age,customer_gender,weekend,num_previous_orders,total_bill
0,Spice Garden,Indian,Lunch,3.0,180.5,10.0,2.3,4.5,28.0,Male,Yes,5.0,486.0
1,Pizza Palace,Italian,Dinner,2.0,350.0,0.0,5.1,3.8,34.0,Female,No,12.0,700.0
2,Burger Barn,American,Lunch,4.0,220.0,15.0,1.8,4.2,22.0,Male,Yes,2.0,748.0
3,Sushi Stop,Japanese,Dinner,5.0,410.0,5.0,7.2,4.9,41.0,Female,No,20.0,1947.5
4,Spice Garden,Indian,Breakfast,1.0,90.0,0.0,2.3,4.5,19.0,Male,No,0.0,90.0

In [30]:
df.corr(numeric_only=True)['total_bill'].sort_values(ascending=False)

total_bill              1.000000
avg_item_price          0.999999
delivery_rating         0.113678
delivery_distance_km    0.112503
discount_percent        0.022588
num_previous_orders    -0.009901
customer_age           -0.015320
num_items              -0.027445
Name: total_bill, dtype: float64

In [31]:
df['customer_gender']=df['customer_gender'].str.lower()

In [32]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cols=['customer_gender','weekend']
for col in cols:
    df[col]=le.fit_transform(df[col])

In [33]:
df.head()

,restaurant_name,cuisine_type,meal_time,num_items,avg_item_price,discount_percent,delivery_distance_km,delivery_rating,customer_age,customer_gender,weekend,num_previous_orders,total_bill
0,Spice Garden,Indian,Lunch,3.0,180.5,10.0,2.3,4.5,28.0,1,1,5.0,486.0
1,Pizza Palace,Italian,Dinner,2.0,350.0,0.0,5.1,3.8,34.0,0,0,12.0,700.0
2,Burger Barn,American,Lunch,4.0,220.0,15.0,1.8,4.2,22.0,1,1,2.0,748.0
3,Sushi Stop,Japanese,Dinner,5.0,410.0,5.0,7.2,4.9,41.0,0,0,20.0,1947.5
4,Spice Garden,Indian,Breakfast,1.0,90.0,0.0,2.3,4.5,19.0,1,0,0.0,90.0

In [34]:
df['cuisine_type']=df['cuisine_type'].str.lower()
df['meal_time']=df['meal_time'].str.lower()

In [35]:
df = pd.get_dummies(
    df,
    columns=['restaurant_name', 'cuisine_type', 'meal_time'],
    drop_first=True   # Avoids dummy variable trap
)

print(df.head())

   num_items  avg_item_price  discount_percent  delivery_distance_km  \
0        3.0           180.5              10.0                   2.3
1        2.0           350.0               0.0                   5.1
2        4.0           220.0              15.0                   1.8
3        5.0           410.0               5.0                   7.2
4        1.0            90.0               0.0                   2.3

   delivery_rating  customer_age  customer_gender  weekend  \
0              4.5          28.0                1        1
1              3.8          34.0                0        0
2              4.2          22.0                1        1
3              4.9          41.0                0        0
4              4.5          19.0                1        0

   num_previous_orders  total_bill  ...  restaurant_name_Sushi Stop  \
0                  5.0       486.0  ...                       False
1                 12.0       700.0  ...                       False
2                  2.0       748.0  ...                       False
3                 20.0      1947.5  ...                        True
4                  0.0        90.0  ...                       False

   restaurant_name_Taco Town  cuisine_type_chinese  cuisine_type_healthy  \
0                      False                 False                 False
1                      False                 False                 False
2                      False                 False                 False
3                      False                 False                 False
4                      False                 False                 False

   cuisine_type_indian  cuisine_type_italian  cuisine_type_japanese  \
0                 True                 False                  False
1                False                  True                  False
2                False                 False                  False
3                False                 False                   True
4                 True                 False                  False

   cuisine_type_mexican  meal_time_dinner  meal_time_lunch
0                 False             False             True
1                 False              True            False
2                 False             False             True
3                 False              True            False
4                 False             False            False

[5 rows x 24 columns]

In [36]:
df.shape

(198, 24)

In [37]:
from sklearn.model_selection import train_test_split
x=df.drop(['total_bill'],axis=1)
y=df['total_bill']

In [38]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [39]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [40]:
y_pred=model.predict(x_test)

In [41]:
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
import numpy as np
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

mae = mean_absolute_error(y_test, y_pred)
print("MAE:", mae)
print("MSE",mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 95.44925116121166
MSE 14100.597026962781
RMSE: 118.74593478078641
R2 Score: 0.8944671760621253

In [42]:
import joblib

joblib.dump(model,'model.pkl')

['model.pkl']